// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5h45ryKg5zbE5ZfOkOGIxn9bhoYx5qFo',
    appId: '1:956428920918:web:49fe5f98ccc896bab8b3f7',
    messagingSenderId: '956428920918',
    projectId: 'social-media-40d6c',
    authDomain: 'social-media-40d6c.firebaseapp.com',
    storageBucket: 'social-media-40d6c.firebasestorage.app',
    measurementId: 'G-RJY2YMEZSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnte6MTu7zJRs5dpfmDpDqwbSryEN8LhQ',
    appId: '1:956428920918:android:d9bead75819b6ab9b8b3f7',
    messagingSenderId: '956428920918',
    projectId: 'social-media-40d6c',
    storageBucket: 'social-media-40d6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd1JcUlDILiTIOESqcglYM4VpD64VpP18',
    appId: '1:956428920918:ios:701641d4d0b6e484b8b3f7',
    messagingSenderId: '956428920918',
    projectId: 'social-media-40d6c',
    storageBucket: 'social-media-40d6c.firebasestorage.app',
    iosClientId: '956428920918-57gt9gqgqu0ina3q7ugkvcfiuipm1lut.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd1JcUlDILiTIOESqcglYM4VpD64VpP18',
    appId: '1:956428920918:ios:701641d4d0b6e484b8b3f7',
    messagingSenderId: '956428920918',
    projectId: 'social-media-40d6c',
    storageBucket: 'social-media-40d6c.firebasestorage.app',
    iosClientId: '956428920918-57gt9gqgqu0ina3q7ugkvcfiuipm1lut.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5h45ryKg5zbE5ZfOkOGIxn9bhoYx5qFo',
    appId: '1:956428920918:web:f60c448d8c6231bcb8b3f7',
    messagingSenderId: '956428920918',
    projectId: 'social-media-40d6c',
    authDomain: 'social-media-40d6c.firebaseapp.com',
    storageBucket: 'social-media-40d6c.firebasestorage.app',
    measurementId: 'G-0P3JP7J2HC',
  );
}
